# Generated by Django 5.1 on 2024-08-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Festival",
            fields=[
                (
                    "festival_name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("location", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("fee", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("parking_available", models.CharField(max_length=255)),
                ("website_url", models.CharField(max_length=255)),
                ("region_name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "festival_table",
            },
        ),
    ]
